### ISSUE TITLE
requirments.txt dependencies do not match setup.py

### ISSUE THREAD

**Issue by bgardiner** [tus/tus-py-client#21]
The `requirments.txt` dependencies do not match the `setup.py` dependencies. For example, 

| requirements.txt        | setup.py           | package  |
| :------------- |:-------------| :-----|
| 1.11.0     | 1.10.0 | six|
| 2018.1.18     | 2017.7.27.1      |   certifi |
| 2.18.4 | 2.11.1     |   requests |

This is causing issues for me since the versions in the `setup.py` are very old. Moreover, `setup.py` specifies strict dependencies instead of lower bounds.

Questions:
* Is there a reason for the inconsistency between `requirments.txt ` and `setup.py`?
* The `requirements.txt` does not appear to be used by `setup.py` -- what is the purpose of having it in the repo?
* Could we change the dependencies to be lower bounds to enhance the compatibility as packages are updated?

**Comment by bgardiner** [comment]
@Flimm thanks for the response. That makes sense.  I would thus advocate for 
* deleting `requirements.txt` from the repo
* converting the existing dependencies in `setup.py` from strict versions (i.e., `==`) to lower bounds (i.e., `>=`), similar to what is currently done for `requests` and `tinydb` in the existing `setup.py`.

@ifedapoolarewaju any objections? Would such a PR be accepted?

**Comment by Flimm** [comment]
I have two ideas:

1. You could simply rename `requirements.txt` to `test_requirements.txt`, and adjust the `.travis.yml` file to reference the new filename. The new filename I think is much clearer. However, you still aren't testing the code against its real dependencies listed in `setup.py`, and there's a possibility that `test_requirements.txt` and `setup.py` could get out of sync again.

2. You could run `pip install -e .` instead of `pip install -r requirements.txt`. The former command reads `setup.py` and installs the dependencies listed there. You could even run both commands, for instance, `pip install -r test_requirements.txt ; pip install -e .` if you have any additional dependencies you only want to install during testing.

**Comment by bgardiner** [comment]
Third idea:
You can house everything in `setup.py` by creating another section for `tests_require` and/or `extras_require` (and you could make `dev` one of the extras).  This would mitigate the need to have the core dependencies listed twice (and thus eliminate risk of versions being out of sync since you could get rid of the `requirements.txt`).  Then to set up a dev environment, you would do `pip install -e tuspy[dev]` or `pip install -e tuspy[test]`.  See further documentation here: http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by Flimm** [comment]
Looks great!
